version: "3"
services:
  user:
    image: "user:1"
    build: user-service/
    ports:
      - "8081:8081"
    depends_on:
      - db
    env_file:
      - config.env
    volumes:
      - .:/app
  task:
    image: "task:1"
    build: task-service/
    ports:
      - "8082:8082"
    depends_on:
      - db
    env_file:
      - config.env
    volumes:
      - .:/app
  state:
    image: "state:1"
    build: state-service/
    ports:
      - "8083:8083"
    depends_on:
      - db
    env_file:
      - config.env
    volumes:
      - .:/app
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservices-postgres
    ports:
      - "5433:5432"
