version: "3"
services:
  # Servicios para Bogotá
  bogota-user:
    image: "bogota-user:1"
    build: bogota-services/bogota-user-service/
    ports:
      - "8081:8081"
    depends_on:
      - db-bogota
    env_file:
      - config.env
    volumes:
      - .:/app
  bogota-task:
    image: "bogota-task:1"
    build: bogota-services/bogota-task-service/
    ports:
      - "8082:8082"
    depends_on:
      - db-bogota
    env_file:
      - config.env
    volumes:
      - .:/app
  bogota-state:
    image: "bogota-state:1"
    build: bogota-services/bogota-state-service/
    ports:
      - "8083:8083"
    depends_on:
      - db-bogota
    env_file:
      - config.env
    volumes:
      - .:/app
  # Servicios para Medellín
  medellin-user:
    image: "medellin-user:1"
    build: medellin-services/medellin-user-service/
    ports:
      - "8084:8084"
    depends_on:
      - db-medellin
    env_file:
      - config.env
    volumes:
      - .:/app
  medellin-task:
    image: "medellin-task:1"
    build: medellin-services/medellin-task-service/
    ports:
      - "8085:8085"
    depends_on:
      - db-medellin
    env_file:
      - config.env
    volumes:
      - .:/app
  medellin-state:
    image: "medellin-state:1"
    build: medellin-services/medellin-state-service/
    ports:
      - "8086:8086"
    depends_on:
      - db-medellin
    env_file:
      - config.env
    volumes:
      - .:/app
  # Servicios para Cali
  cali-user:
    image: "cali-user:1"
    build: cali-services/cali-user-service/
    ports:
      - "8087:8087"
    depends_on:
      - db-cali
    env_file:
      - config.env
    volumes:
      - .:/app
  cali-task:
    image: "cali-task:1"
    build: cali-services/cali-task-service/
    ports:
      - "8088:8088"
    depends_on:
      - db-cali
    env_file:
      - config.env
    volumes:
      - .:/app
  cali-state:
    image: "cali-state:1"
    build: cali-services/cali-state-service/
    ports:
      - "8089:8089"
    depends_on:
      - db-cali
    env_file:
      - config.env
    volumes:
      - .:/app
  # DB Bogotá
  db-bogota:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db-bogota
    ports:
      - "5433:5432"
    volumes:
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
      - ./sql/data-bogota.sql:/docker-entrypoint-initdb.d/data-bogota.sql
  # DB Bogotá
  db-medellin:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db-medellin
    ports:
      - "5434:5432"
    volumes:
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
      - ./sql/data-medellin.sql:/docker-entrypoint-initdb.d/data-medellin.sql
  db-cali:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db-cali
    ports:
      - "5435:5432"
    volumes:
      - ./sql/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql
      - ./sql/data-cali.sql:/docker-entrypoint-initdb.d/data-cali.sql

  # API
  api:
    image: "api-gateway:1"
    build: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - config.env
    volumes:
      - .:/app